function data = elgsrsplit(data)
% Split GSR data into Tonic and Phasic signals.
%
% The input "data" is a structure generated by running an Edulogger experiment,
% consisting of the following fields:
% Time: The time (s) since the start of the experiment of each sample.
% (double)
% Concern: Whether or not each sample took more than twice the specified
% sample rate to retrieve (logical)
% GSR: Raw electrodermal data from a GSR edulogger (double)
% An additional field for each kind of Edulogger used, containing the
% measurements taken at each point in data.Time.
% 
% The output "data" is the same structure which was inputted, with two
% columns added: Tonic and Phasic, representing the tonic (gradual) and
% phasic (fast) responses within the supplied GSR data.

if isfield(data, 'GSR') % Throw an error if data supplied is not GSR
    sps = round( 1/mean( diff([data.Time]) ) ); % From data, estimate sps which was used
    t = smooth([data.GSR], sps*2, 'moving'); % Use a moving smooth method with a span of 2 seconds to extract tonic signal
    for n = 1:length(data) % For each data point...
        data(n).Tonic = t(n); % Replace data in tonic array with smoothed equivalent
        data(n).Phasic = data(n).GSR - t(n); % Replace data in phasic array with difference between tonic equivalent and original value (this is the phasic signal)
    end
else
    error('Data must have a column of GSR data');
end
