function [sps, spsArray] = elsps(data)
% Estimate samples per second
%
% The input "data" is a structure generated by running an Edulogger experiment,
% consisting of the following fields:
% Time: The time (s) since the start of the experiment of each sample.
% (double)
% Concern: Whether or not each sample took more than twice the specified
% sample rate to retrieve (logical)
% An additional field for each kind of Edulogger used, containing the
% measurements taken at each point in data.Time.
% 
% The output "sps" is the overall overage rate of samples per second,
% rounded to an integer
% The output "spsArray" is a running average of the rate of samples per
% second at each point, with a sampling window of approximately 1s
% (calculated using sps)

valid = ~isnan([data.Time]); % Get indices of non-name timestamps
tdiff = diff([data(valid).Time]); % Get matrix of time difference betwen samples
sps = round(1/mean(tdiff)); % Calculate average rate of samples per second
spsArray = smooth(1./tdiff, sps); % Estimate running average of samples per second (with a scope of approx. 1s)