def elgetval(port, *varargin):
    # Get individual value from specified Eduloggers
    # "port" is the port Eduloggers are connected to, this is visible on the
    # Neulog API window.
    # "loggers" is a one dimensional cell array, with each string specifying
    # the name of a different Edulogger as described in the Neulog API
    # literature:
    # https://neulog.com/wp-content/uploads/2014/06/NeuLog-API-version-7.pdf
    #
    # The output "data" is one row of a structure generated when running an 
    # Edulogger experiment, consisting of one field for each kind of Edulogger 
    # used, containing the measurements taken at each point in data.Time. 
    # Fieldnames should line up with the names specified in "loggers".
    
    import requests
    loggers = list(map(''.join, varargin)); # Convert varargin to list for ease
    preface = 'http://localhost:' + str(port) + '/NeuLogAPI?'; # Construct the string to preface any argument passed to the Eduloggers
    for l in loggers: # For each logger...
        resp = requests.get(preface + 'GetSensorValue:[' + l + '],[1]'); # Send request for sensor value
        val = float(''.join([x for x in resp.text if x in ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.', '-']])); # Extract numeric values
    return val

def elrun(port, dur, sps, *varargin):
    # Run specified Eduloggers for a specified duration at a specified temporal
    # resolution.
    #
    # "port" is the port Eduloggers are connected to, this is visible on the
    # Neulog API window.
    # "dur" is the duration (s) of the clap test, it must be at least 15s for
    # any response to be visible.
    # "sps" is the number of samples the edulogger should take per second, up
    # to a maximum of 5.
    # "loggers" is a one dimensional cell array, with each string specifying
    # the name of a different Edulogger as described in the Neulog API
    # literature:
    # https://neulog.com/wp-content/uploads/2014/06/NeuLog-API-version-7.pdf
    #
    # The output "data" is a structure generated by running an Edulogger experiment,
    # consisting of the following fields:
    # Time: The time (s) since the start of the experiment of each sample.
    # (double)
    # Concern: Whether or not each sample took more than twice the specified
    # sample rate to retrieve (logical)
    # An additional field for each kind of Edulogger used, containing the
    # measurements taken at each point in data.Time. Fieldnames should line up
    # with the names specified in "loggers".
    
    eltypes = numpy.load('eltypes.npy'); # Load possible Edulogger types from file
    loggers = [x for x in varargin if any(x == eltypes)] ; # Extract variable inputs matching valid types
    